### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by jr-cologne** [jr-cologne/CryptoStatus#7]
Refactoring your own code is always hard.

This is why I would highly appreciate any sort of help in order to finally refactor the code of this project.

Your task would be to go through the files looking for code that could be improved. This can regard to readability issues, performance optimizations, best practices, or whatever else.

For instance, there is probably a better way to make use of Exceptions. Currently, every class has a corresponding Exception class and I'm always explicitly setting an error code when throwing an Exception, but there is no real system behind that. I don't think that's corresponding to any best practices for dealing with Exceptions. So, feel free to help me out.

And this is just one example. I guess there is much more which could be refactored.

In case you would like to contribute, feel free to leave a comment down here letting me know what you are going to do. Then, fork this Repository, make your changes in a branch named `your-username_refactor` and open up a Pull Request to merge your changes into this Repository.

Thank you & Happy coding! 🎉

**Comment by dangenendt** [comment]
I'd like to have a look into this one. Already checked out your code. 
First thing i've noticed is that you are mixing up some coding styles instead of using one specific. 
My recommendation is to use the PSR12 standard (see https://www.php-fig.org/psr/). 
If that is ok for you i would like to execute PHP CodeSniffer with PSR-12 settings. 

After that i'll have a deeper look into the code

**Comment by muffomat** [comment]
Hi jr-cologne!
Please see PR #21 
Using a common parent exception class can be useful if you want to catch all project exceptions - it helps identifying them.
Also using strict_types might be a good idea systemwide to handle types more propery, but that's up to you ;-)

**Comment by jr-cologne** [comment]
Hi @dangenendt and @muffomat,
thank you very much for your contributions.
I am going to review and comment on your changes in the PRs itself.
Best regards,
@jr-cologne
